### ISSUE TITLE
Screenshot of your phone homescreen.

### ISSUE THREAD

**Issue by AchoArnold** [sholladay/ama#1]

**Comment by sholladay** [comment]
My homescreen is simple and relatively uncluttered, but useful. It also has to be peaceful. No nagging notifications allowed. The feet are mine, sitting on a beach in [Aruba](https://en.wikipedia.org/wiki/Aruba).

![sholladay-phone-homescreen](https://cloud.githubusercontent.com/assets/3674950/21517611/60cad2d0-ccae-11e6-918d-4084e1082c6e.png)

**Comment by sholladay** [comment]
My homescreen is simple and relatively uncluttered, but useful. It also has to be peaceful. No nagging notifications allowed. The feet are mine, sitting on a beach in [Aruba](https://en.wikipedia.org/wiki/Aruba).

<img alt="Seth Holladay's phone homescreen" src="https://cloud.githubusercontent.com/assets/3674950/21517611/60cad2d0-ccae-11e6-918d-4084e1082c6e.png" width="60%">

**Comment by AchoArnold** [comment]
Thanks 👍
